language: python
python:
  - "2.7"
# command to install dependencies, e.g. 
install: 
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
addons:
  apt_packages:
    - libhdf5-serial-dev
# command to run tests, e.g. python setup.py test
#script:  python setup.py test
script: coverage run --source=pyspectral setup.py test
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
after_success: coveralls
deploy:
  provider: pypi
  user: adybbroe
  password:
    secure: A/DAh5K6A1UzARPWsiNL+qiyLfHd1dS2fhmZlE0SNcS0zN1CalyY2s7znVKTE15fSF0oV/jah/jy1PQIMBFFbAhpc6nmnDx3DxJ3d9RWxGE2hLWKn9tYUHQ07k7oiRFrwQe2bEJlaLBQfBOZ/DIe4Umc3osC65UINX03oOHsPFI=
  on:
    tags: true
    repo: pytroll/pyspectral
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
